common_port = {
    1: ""
}

all_ports = {
    1: "TCP Port Server Multiplexer",
    5: "Remote Job Entry",
    7: "Echo Protocol",
    9: "Discard Protocol/Wake-on-LAN",
    11: "Systat Server - Active User",
    13: "Daytime Protocol",
    15: "Previously netstat service",
    17: "Quote of the Day",
    18: "Message Send Protocol",
    19: "Character Generator Protocol (CHARGEN)",
    20: "File Transfer Protocol - FTP Data Transfer",
    21: "File Tansfer Protocol - FTP Control (command)",
    22: "Secure Shell, Secure Login, SCP, SFTP & Port Forwarding",
    23: "Telnet Protocol - Unencrypted Text Coms",
    25: "Simple Mail Transfer Protocol - SMTP",
    28: "Palo Alto Networks, Panorama High Availability (HA) Sync Encrypted Port",
    37: "Time Protocol",
    42: "Host Name Server Protocol",
    43: "WHOIS Protocol",
    47: "Reserved",
    49: "TACACS Login Host Protocol",
    51: "Reserved",
    52: "Xerox Network Systems (XNS) Time Protocol",
    53: "Domain Name System (DNS)",
    54: "Xerox Network Systems (XNS) Clearinghouse",
    56: "Xerox Network Systems (XNS) Authentication Protocol",
    58: "Xeros Network Systems (XNS) Mail",
    61: "Reserved",
    67: "Bootstrap Protocol (BOOTP) Server",
    68: "Bootstrap Protocol (BOOPT) Client",
    69: "Trivial File Transfer Protocol (TFTP)",
    70: "Gopher Protocol",
    71: "NERTJS Protocol",
    72: "NERTJS Protocol",
    73: "NERTJS Protocol",
    74: "NERTJS Protocol",
    79: "Finger Protocol",
    80: "Hypertext Transfer Protocol (HTTP)",
    81: "TorPark Onion Routing",
    82: "TorPark Control",
    83: "MIT ML Device, Network File System",
    88: "Kerberos Authentication System",
    90: "PointCast (dotcom)",
    95: "SUPDUP, Terminal-independent Remote Login",
    101: "NIC Host Name",
    102: "ISO Transport Service Access Point (TSAP)",
    104: "Digital Imaging and Communications in Medicine (DICOM) also port 11112",
    105: "CCSO Nameserver",
    106: "macOS Server, macOS Password Server",
    107: "Remote User Telnet Service (RTelnet)",
    108: "IBM System Network Architechure (SNA) Gateway Access Server",
    109: "Post Office Protocol version 2 (POP2)",
    110: "Post Office Protocol version 3 (POP3)",
    111: "Open Network Computing Remote Procedure Call (ONC RPC)",
    113: "Indent - Authentication Service/Identification Protocol // Authentication Service (auth)",
    115: "Simple File Transfer Protocol",
    117: "UUCP Mapping Project (path service)",
    118: "Structed Query Language (SQL) Services",
    119: "Network News Transfer Protocol (NNTP)",
    123: "Network Time Protocol",
    126: "NXEdit",
    135: "Microsoft EPMAP (End Point Mapper) - DCE/RCP Locator Service",
    137: "NetBIOS Name Service",
    138: "NetBIOS Datagram Service",
    139: "NetBIOS Session Service",
    143: "Internet Message Access Protocol (IMAP)",
    152: "Background File Transfer Program (BFTP)",
    153: "Simple Gateway Monitoring Protocol (SGMP)",
    156: "Structured Query Language (SQL) Service",
    158: "Distributed Mail Language Protocol (DMSP/Pcmail)",
    161: "Management Protocol (SNMP)",
    162: "Simple Network Management Protocol Trap (SNMPTRAP)",
    170: "Network PostScript Print Server",
    177: "X Display Manager Control Protocol (XDMCP)",
    179: "Border Gateway Protocol (BGP)",
    194: "Internet Relay Chat (IRC)",
    199: "SNMP Unix Multiplexer (SMUX)",
    201: "AppleTalk Routing Maintenance",
    209: "Quick Mail Transfer Protocol",
    210: "ANSI Z39.50",
    213: "Internetwork Packet Exchange (IPX)",
    218: "Message Posting Protocol (MPP)",
    220: "Internet Message Access Protocol (IMAP) version 3",
    259: "Efficient Short Remote Operations (ESRO)",
    262: "Arcisdms",
    264: "Border Gateway Multicast Protocol (BGMP)",
    280: "http-mgmt",
    300: "ThinLinc Web Access",
    308: "Novastor Online Backup",
    311: "macOS Server Admin",
    312: "macOS Xsan administration",
    318: "PKIX Time Stamp Protocol (TSP)",
    319: "Precision Time Protocol (PTP) event messages",
    320: "Precision Time Protocol (PTP) general messages",
    350: "Mapping of Airline Traffic over Internet Protocol (MATIP)",
    351: "MATIP type B",
    356: "cloanto-net-1",
    366: "On-Demand Mail Relay (ODMR)",
    370: "securecast1",
    371: "ClearCase albd",
    376: "Amiga Envoy Network Inquiry Protocol",
    383: "HP Data Alarm Manager",
    384: "A Remote Network Server System",
    387: "AURP (AppleTalk Update-based Routing Protocol)",
    388: "Unidata LDM",
    399: "Digital Equipment Corporation DECnet+",
    401: "Uninterruptible power supply (UPS)",
    427: "Service Location Protocol (SLP)",
    433: "NNTP - Network News Transfer Protocol",
    434: "Mobil IP Agent",
    443: "Hypertext Transfer Protocol Secure (HTTPS)",
    444: "Simple Network Paging Protocol (SNPP) RFC 1568",
    445: "Microsoft-DS (Directory Services) Active Directory, Windows Shares // SMB File sharing",
    464: "Kerberos Change/Set Password",
    465: "SMTP over implicit SSl // URL Rendezvous Directory for Cisco SSM // Authenticated SMTP over TLS/SSL (SMTPS)",
    475: "tcpnethaspsrv, Aladdin Knowledge Systems Hasp services",
    476: "Centro Software ERP ports",
    477: "Centro Software ERP ports",
    478: "Centro Software ERP ports",
    479: "Centro Software ERP ports",
    480: "Centro Software ERP ports",
    481: "Centro Software ERP ports",
    482: "Centro Software ERP ports",
    483: "Centro Software ERP ports",
    484: "Centro Software ERP ports",
    485: "Centro Software ERP ports",
    486: "Centro Software ERP ports",
    487: "Centro Software ERP ports",
    488: "Centro Software ERP ports",
    489: "Centro Software ERP ports",
    490: "Centro Software ERP ports",
    491: "GO-Global remote access and application publishing software",
    497: "Retrospect",
    500: "internet Security Association and Key Management Protocol (ISAKMP) / Internet Key Exchange (IKE)",
    502: "Modbus Protocol",
    504: "Citadel",
    510: "FirstClass Protocol (FCP)",
    512: "Rexec, Remote Process Execution // comcast, together with biff",
    513: "rlogin // Who",
    514: "Remote Shell // Syslog",
    515: "Line Printer Daemon (LPD) print service",
    517: "Talk",
    518: "NTalk",
    520: "efs extended file name server // Routing Information Protocol (RIP)",
    521: "Routing Information Protocol Next Generation (RIPing)",
    524: "NetWare Core Protocol (NCP)",
    525: "Timed, Timeserver",
    530: "Remote procedure call (RPC)",
    532: "netnews",
    533: "netwall for Emergency Broadcasts",
    540: "Unix-to-Unix Copy Protocol",
    542: "commerce",
    543: "klogin, Kerberos login",
    544: "kshell, Kerberos Remote shell",
    546: "DHCPv6 client",
    547: "DHCPv6 server",
    548: "Apple Filing Protocol (AFP) over TCP",
    550: "new-rwho, new-who",
    554: "Real Time Streaming Protocol (RTSP)",
    556: "Remotefs, RFS, rfs_server",
    560: "rmonitor, Remote Monitor",
    561: "monitor",
    563: "NNTP over TLS/SSL (NNTPS)",
    564: "9p (Plan 9)",
    587: "email message submission (SMTP)",
    591: "FileMaker 6.0 (and later) Web Sharing (HTTP Alternative, also see port 80)",
    593: "HTTP RPC Ep Map, Remote procedure call over Hypertext Transfer Protocol",
    601: "Reliable Syslog Service",
    604: "TUNNEL profile; BEEP peers",
    623: "ASF Remote Management and Control Protocol",
    625: "Open Directory Proxy (ODProxy)",
    631: "Internet Printing Protocol (IPP) // Common Unix Printing System (CUPS)",
    635: "RLZ DBase",
    636: "Lightweight Directory Access Protocol over TLS/SSL (LDAPS)",
    639: "Multicast Source Discovery Protocol, MSDP",
    641: "SupportSoft Nexus Remote Command (control/listening)",
    643: "SANity",
    646: "Label Distribution Protocol (LDP) - used in MPLS networks",
    647: "DHCP Failover protocol",
    648: "Registry Registrar Protocol (RRP)",
    651: "IEEE-MMS",
    653: "SupportSoft Nexus Remote Command (data)",
    654: "Media Management System (MMS) Media Management Protocol (MMP)",
    655: "Tinc VPN daemon",
    657: "IBM RMC (Remote monitoring and Control) protocol",
    660: "macOS Server administration, version 10.4 and earlier",
    666: "Doom, videogame // airserv-ng, aircrack-ng's server for remote-controlling wireless devices",
    674: "Application Configuration Access Protocol (ACAP)",
    688: "REALM-RUSD (ApplicationWare Server Application Management Protocol)",
    690: "Velno Application Transfer Protocol (VATP)",
    691: "MS Exchange Routing",
    694: "Linux-HA high-availability heartbeat",
    695: "IEEE Media Management System over SSL (IEEE-MMS-SSL)",
    698: "Optimized Link State Routing (OLSR)",
    700: "Extensible Provisioning Protocol (EPP)",
    701: "Link Management Protocol (LMP)",
    702: "IRIS (Internet Registry Information Service)",
    706: "Secire Internet Live Conferencing (SILC)",
    711: "Cisco Tag Distribution Protocol",
    712: "Topology Broadcast based on Reverse-Path Forwarding routing protocol",
    749: "Kerberos (protocol) administration",
    750: "kerberos-iv, Kerberos version IV",
    753: "Reverse Routing Header (RRH) // userreg_server, Kerberos usereg server",
    754: "tell send // krb5_prop, Kerberos v5 slave propagation",
    760: "krbupdate [kreg], Kerberos registration",
    782: "Conserver serial-console management server",
    783: "SpamAssassin spamd daemon",
    800: "mdbs-daemon",
    802: "MODBUS/TCP Security",
    808: "Microsoft Net.TCP Port Sharing Service",
    829: "Certificate Management Protocol",
    830: "NETCONF over SSH",
    831: "NETCONF over BEEP",
    832: "NETCONF for SOAP over HTTPS",
    833: "NETCONF for SOAP over BEEP",
    843: "Adobe Flash",
    847: "DHCP Failover Protocol",
    848: "Group Domain Of Interpretation (GDOI) protocol",
    853: "DNS over TLS (RFC 7858)",
    860: "iSCSI (RFC 3720)",
    861: "OWAMP control (RFC 4656)",
    862: "TWAMP control (RFC 5357)",
    873: "rsync file synchronization protocol",
    888: "cddbp CD DataBase (CDDB) Protocol (CDDBP)",
    897: "Brocade SMI-S RPC",
    898: "Brocade SMI-S RPC SSL",
    902: "VMWare ESXi",
    903: "VMWare ESXi",
    953: "BIND remote name daemon control (RNDC)",
    981: "Remote HTTPS management for firewall devices running embedded Check Point VPN-1 software",
    987: "Sony PlayStation Wake On Lan // Microsoft Remote Web Workplace - Windows Small Business Server",
    988: "Lustre (file system) Protocol (data)",
    989: "FTPS Protocol (data), FTP over TLS/SSL",
    990: "FTPS Protocol (control), FTP over TLS/SSL",
    991: "Netnews Administration System (NAS)",
    992: "Telnet protocol over TLS/SSL",
    994: "Internet Message Access Protocol over TLS/SSL (IMAPS)",
    995: "Post Office Protocol 3 over TLS/SSL (POP3S)",
    1010: "ThinLinc web-based administration interface",
    1023: "z/OS Network File Syetem (NFS) (potentially ports 991 - 1023)",
    1024: "Reserved",
    1027: "Reserved // Native IPv6 behind IPv4-to-IPv4 NAT",
    1028: "Reserved",
    1029: "Microsoft DOOM Services",
    1058: "nim IBM AIX Network Installation Manager",
    1059: "nimreg, IBM AIX Network Installation Manager (NIM)",
    1080: "SOCKS Proxy",
    1085: "WebObjects",
    1098: "rmiactivation, Java remote method invocation (RMI) activation",
    1099: "rmiregistry Java method invocation (RMI) registry",
    1109: "Kerberos Post Office Protocol (KPOP)",
    1113: "Licklider Transmission Protocol (LTP) delay tolerant networking protocol",
    1119: "Battle.net chat/game protocol, used by Blizzards games",
    1167: "Cisco IP SLA (Service Assurance Agent)",
    1194: "OpenVPN",
    1198: "The cajo project Free dynamic transparent distributed computing in Java",
    1214: "Kazaa",
    1220: "QuickTime Streaming Server administration",
    1234: "VLC media player default port to UDP/Rtp stream",
    1241: "Nessus Security Scanner",
    1270: "Microsoft System Center Operation Manager (SCOM)",
    1293: "Windows RxMon.exe",
    1311: "Dell OpenManage HTTPS",
    1314: "Festival Speech Synthesis System server",
    1319: "AMX ICSP (Protocol for communications with AMX control systems devices)",
    1337: "neo4j-shell // Strapi // Sails.js Default Port // WASTE Encrypted File Sharing Program",
    1341: "Qubes (Manufacturing Execution System)",
    1344: "Internet Content Adaptation Protocol",
    1352: "IBM Lotus Notes/Domino (RPC) protocol",
    1360: "Mimer SQL",
    1414: "IBM WebSphere MQ - formerly known as MQSeries",
    1417: "Timbuktu Service 1 Port",
    1418: "Timbuktu Service 2 Port",
    1419: "Timbuktu Service 3 Port",
    1420: "Timbuktu Service 4 Port",
    1431: "Reverse Gossip Transport Protocol (RGTP)",
    1433: "Microsoft SQL Server database management system (MSSQL) server",
    1434: "Microsoft SQL Server database management system (MSSQL) monitor",
    1481: "AIRS data interchange",
    1492: "Sid Meier's CivNet",
    1494: "Citrix Independant Compution Architecture (ICA)",
    1500: "IBM Tivoli Storage Manager server",
    1501: "IBM Tivoli Storage Manager Client scheduler",
    1503: "Windows Live Messenger (Whiteboard and scheduler)",
    1512: "Microsoft's Windows Internet Name Service (WINS)",
    1513: "Garena game client",
    1521: "Oracle database default listener",
    1524: "ingreslock",
    1527: "Oracle database default listener // Apache Derby Network Service",
    1533: "IBM Sametime Virtual Places Chat",
    1534: "Eclipse Target Communication Framework",
    1540: "1C:Enterprise server agent (ragent)",
    1541: "1C:Enterprise master cluster manager (rmngr)",
    1542: "1C:Enterprise configuration repository server",
    1545: "1C:Enterprise cluster administration server (RAS)",
    1547: "Laplink",
    1550: "Gadu-Gadu (direct client-to-client)",
    1560: "1C:Enterprise cluster working processes",
    1581: "MIL STD 2045-47001 VMF // IBM Tivoli Storage Manager web client",
    1582: "IBM Tivoli Storage Manager Server web interace",
    1583: "Percasive PSQL",
    1589: "Cisco VLAN Query Protocol (VQP)",
    1590: "1C:Enterprise cluster working processes",
    1604: "DarkComet remote administration tool (RAT)",
    1626: "iSketch",
    1627: "iSketch",
    1628: "LonTalk normal",
    1629: "LonTalk urgent",
    1645: "Early deployment of RADIUS",
    1646: "Old radacct port",
    1666: "Perforce",
    1677: "Novell GroupWise client in client/server access mode",
    1688: "Microsoft Key Management Service (KMS) for windows activation",
    1701: "Layer 2 Forwarding Protocol // Layer 2 Tuneling Protocol",
    1707: "Windward Studios Games (vdmplay) // L2TP/IPsec for establish an inital connection",
    1716: "America's Army, a massively multiplayer online game",
    1719: "H.323 registration and alternate communuication",
    1720: "H323 call signaling",
    1723: "Point-to-Point Tunneling Protocol (PPTP)",
    1755: "Microsoft Media Services (MMS, ms-streaming)",
    1761: "Novell ZENworks",
    1776: "Emergency management informAtyion system",
    1783: "Reserved - Decomissioned [sic] Port 04/14/00, ms",
    1801: "Microsoft Message Queing",
    1812: "RADIUS auth protocol - radius",
    1813: "RADIUS accounting protocol - radius-acct",
    1863: "Microsoft Notification Protocol (MSNP)",
    1880: "Node-RED",
    1883: "MQTT (formerly MQ Telemetry Transport)",
    1900: "Simple Service Discovery Protocol (SSDP)",
    1935: "Macromedia Flask Communication Server MX // Real Time Messagign Protocol (RTMP)",
    1965: "Gemini - Gap fill between Gopher and HTTP",
    1967: "Cisco IOS IP Service Level Agreements (IP SLAs) Control Protocol",
    1970: "Netop Remote Control",
    1972: "InterSystems Cache",
    1984: "Big Brother",
    1985: "Cisco hot Standby Router Protocol (HSRP)",
    1998: "Cisco X.25 over TCP (XOT) service",
    2000: "Cisco Skinny Client Control Protocol (SCCP)",
    2010: "Artemis: Spaceship Bridge Simulator",
    2033: "Civilization IV Multiplayer",
    2049: "Network File System (NFS)",
    2056: "Civilation IV Multiplayer",
    2080: "Autodesk NLM (FLEXlm)",
    2082: "cPanel default",
    2083: "Secure RADIUS Service (radsec) // cPanel default SSL",
    2086: "GNUnet // WebHost Manager default",
    2087: "WebHost Manager default SSL",
    2095: "cPanel default web mail",
    2096: "cPanel default SSL web mail",
    2100: "Warzone 2100 multiplayer",
    2101: "Network Transport of RTCM via Internet Protocol (NTRIP)",
    2102: "Zephyr Notification Service server",
    2103: "Zephyr Notification Service serv-hm connection",
    2104: "Zephyr Notification Service hostmanager",
    2123: "GTP control messages (GTP-C)",
    2142: "TDMoIP (TDM over IP)",
    2152: "GTP user data messages (GTP-U)",
    2159: "GDB remote debug port",
    2181: "Apache Zookeeper default client port",
    2195: "Apple Push Notifcation Service",
    2196: "Apple Push Notification Service, feedback service",
    2210: "NOAAPORT Broadcast Network",
    2211: "EMWIN",
    2221: "ESET anit-virus updates",
    2222: "DirectAdmin Access // ESET Remote administration",
    2226: "ESET Remote administration",
    2240: "General Dynamics Remote Encryptor Configuration Information Protocol (RECIPe)",
    2261: "CoMotion master",
    2262: "CoMotion backup",
    2302: "ArmA multiplayer // Halo: Combat Evolved multiplayer",
    2303: "ArmA multiplayer (default port for game + 1) // Halo: Combat Evolved multiplayer listener",
    2305: "ArmA multiplayer (default port for game + 3)",
    2351: "AIM game LAN network port",
    2368: "Ghost (blogging platform)",
    2369: "Default for BMC Control-M/Server Configuration Agent",
    2370: "Default for BMC Control-M/Server Control-M/Server",
    2372: "Default for K9 Web Protection/parental controls, content filtering agent",
    2375: "Docker REST API (plain)",
    2376: "Docker REST API (SSL)",
    2377: "Docker Swarm cluster management communications",
    2379: "CoreOS etcd client communication // KGS Go Server",
    2380: "CoreOS etcd server communication",
    2389: "OpenView Session Mgr",
    2399: "FileMaker Data Access Layer (ODBC/JDBC)",
    2401: "CVS version control system password-based server",
    2404: "IEC 60870-5-105",
    2424: "OrientDB database listening for binary client connection",
    2427: "Media Gateway Control Protocol",
    2447: "ovwdb - OpenView Network Node Manager (NNM) daemon",
    2459: "XRPL",
    2480: "OrentDB DataBase Listening for HTTP client connections",
    2483: "Oracle database listening for insecure client connections to listener, replaces port 1521",
    2484: "Oravcle database lisetning for SSL client connection to listener",
    2500: "NetFS communications",
    2501: "NetFS probe",
    2535: "Multicast Address Dynamic Client Allocation Protocol (MADCAP)",
    2541: "LonTalk/IP",
    2546: "EVault data protection services",
    2593: "Ultima Online Services",
    2598: "Citrix Independant Computing Architechure (Ica)",
    2599: "Ultima Online Servers",
    2628: "DICT",
    2638: "SQL Anywhere database server",
    2710: "XBT Tracker",
    2727: "Media Gateway Control Protocol (MGCP) call agent",
    2775: "Short Message Peer-to-Peer",
    2809: "corbalic:iiop URL per COBRA 3.0.3",
    2811: "gsi ftp, GridFTP spec",
    2827: "I2P BOB Bridge",
    2944: "Megaco text H.248",
    2945: "Megaco binary (ASN.1) H.248",
    2947: "gpsd GPS daemon",
    2948: "WAP push Multimedia Messaging Service (MMS)",
    2949: "WAP push secure (MMS)",
    2967: "Symantex System Centre agaent (SSC-AGENT)",
    3000: "Cloud9 IDE Server // Ruby on Rails dev default // Meteor dev default // Resilio Sync // Distributed Interactive Simulation (DIS) // Create React App // GOGS (self-hosted GIT Service)",
    3004: "iSync",
    3020: "Common Internet File System (CIFS)",
    3050: "gds-db (Interbase/Firebird database)",
    3052: "APC PowerChute Network",
    3074: "Xbox LIVE and Games for Windows - LIVE",
    3101: "Blackberry Enterprise Server communication protocol",
    3128: "Squid caching web proxy",
    3225: "Fibre Channel over IP (FCIP)",
    3233: "WhiskerControl research control protocol",
    3260: "iSCSI",
    3268: "msft-gc, Microsoft Global Catalog (LDAP service)",
    3269: "msft-gc-ssl, Microsoft Global Catalog over SSL",
    3283: "Net Assistant // Apple Remote Desktop",
    3290: "Virtual Air Traffic Sim (VATSIM) network voice communication",
    3305: "Odette File Transfer Protocol (OFTP)",
    3306: "MySQL database system",
    3323: "DECE GEODI Server",
    3332: "Thundercloud DataPath Overlay Control",
    3333: "Eggdrop, IRC bot default port // Network Caller ID // CruiseControl.rb",
    3351: "Pervasive PSQL",
    3386: "GTP' 3GPP GSM/UMTS CDR logging protocol",
    3389: "Microsoft Terminal Server (RDP)",
    3396: "Novell NDPS Printer Agent",
    3412: "xmlBlaster",
    3423: "Xware xTrm Communication Protocol",
    3424: "Xware xTrm Communication Protocol over SSL",
    3435: "Pacom Security User Port",
    3455: "Resource Reservation Protocol (RSVP)",
    3478: "STUN - a protocol for NAT traversal // TURN - a protocol for NAT traversal (extension to STUN) // STUN Behavior Discovery",
    3479: "Playstation Network",
    3480: "Playstation Network",
    3483: "Slim Devices discovery protocol // Slim Devices SlimProto protocol",
    3483: "Network UPS Tools (NUT)",
    3503: "MPLS LSP-echo Port",
    3516: "Smartcard Port",
    3527: "Microsoft Message Queuing",
    3535: "SMTP alternative",
    3544: "Teredo tunneling",
    3551: "Apcupsd Information Port",
    3601: "SAP Message Server Port",
    3632: "Distcc, disributed compiler",
    3645: "Cyc",
    3658: "Apple SASL, used by macOS Server Password Server // Battlefield 4",
    3667: "Information Exchange",
    3689: "Digital Audio Access Protocol (DAAP) used by Apple iTunes and AirPlay",
    3690: "Subversion (SVN) version control system",
    3702: "Web Services Dynamic Discovery (WS-Discovery), used by various components of Windows Vista and later",
    3724: "Some Blizzard games // Club Penguin",
    3725: "Netia NA-ER Port",
    3749: "CimTrak registered port",
    3768: "RBLchecked server port",
    3784: "Bidirectional Forwarding Detection (BFD) for IPv4 and IPv6 (Single Hop) (RFC 5881)",
    3785: "VoIP program used by Ventrilo",
    3799: "RADIUS change of authorization",
    3804: "Harman Professional HiQnet protocol",
    3825: "RedSeal Networks client/server connection",
    3826: "WarMUX game server // RedSeal Network client/server connection",
    3835: "RedSeal Network client/server connection",
    3830: "System Management Agent, used by Cerner",
    3856: "ERP Server Application used by F10 Software",
    3880: "IGRS",
    3868: "Diameter base protocol (RFC 3588)",
    3872: "Oracle Enterprise Manager Remote Agent",
    3900: "udt_os, IBM UniData UDT OS",
    3960: "Warframe online interaction",
    3962: "Warframe online interaction",
    3978: "OpenTTD game (masterserver and content service) // Palo Alto Networks' Panorama management of firewalls and log collectors & pre-PAN-OS",
    3979: "OpenTTD game",
    3999: "Norman distributed scanning service",
    4000: "Diablo II game",
    4001: "Microsoft Ants game // CoreOS etcd client communication",
    4018: "Protocol information and warnings",
    4035: "IBM rational Developer for System z Remote System Explorer Daemon",
    4045: "Solaris locked NFS lock daemon/manager",
    4050: "Mud Master Chat protocol (MMCP) - Peer-to-peer communications between MUD clients",
    4069: "Minger Email Address Varification Protocol",
    4070: "Amazon Echo Dot (Amazon Alexa) streaming connection with spotify",
    4089: "Kerio",
    4093: "PxPlus Client server interface ProvideX",
    4096: "Ascom Timeplex Bridge Relay Element (BRE)",
    4105: "Shofar (ShofarNexus)",
    4111: "Xgrid",
    4116: "Smartcard-TLS",
    4125: "Micrsoft Remote Web Workplace administration",
    4172: "Teradici PCoIP",
    4190: "ManageSieve",
    4195: "AWS protocol for cloud remoting solution",
    4197: "Harman International's HControl protocol for control and monitoring of Audio, Video, Lighting and Control equipment",
    4198: "Couch Potato Android app",
    4201: "TinyMUD and various derivatives",
    4222: "NATS server default port",
    4226: "Aleph One, a computer game",
    4242: "Orthanc - DICOM server // Quassel distributed IRC client",
    4243: "Docker implementations, redistributions, and setups default // CrashPlan",
    4244: "Viber",
    4303: "Simple Railroad Command Protocol (SRCP)",
    4307: "TrueConf Client - TrueConf Server media data exchange",
    4321: "Referral Whois (RWhois) Protocol",
    4444: "Oracle WebCenter Content: Content Server - Intradoc Socket port // Metasploit's default listener port // Xvfb X server virtual frame buffer service // I2P HTTPS proxy",
    4445: "I2P HTTPS proxy",
    4486: "Intergrated Client Message Service (ICMS)",
    4488: "Apple Wide Area Connectivity Service - used by Back to My Mac",
    4500: "IPSec NAT Traversal (RFC 3947, RFC 4306)",
    4502: "Microsoft Silverlight connectable ports under non-elevated trust",
    4505: "Salt master",
    4506: "Salt master",
    4534: "Microsoft Silverlight connectable ports under non-elevated trust",
    4560: "default Log4j socketappender port",
    4567: "Sinatra default server port in development mode (HTTP)",
    4569: "Inter-Asterisk eXchange (IAX2)",
    4604: "Identy Registration Protocol",
    4605: "Direct End to End Secure Chat Protocol",
    4610: "QualiSystems TestShell Suite Services",
    4640: "QualiSystems testShell Suite Services",
    4662: "OrbitNet Message Service // Default for older versions of eMule",
    4664: "Google Desktop Search",
    4672: "Default for older versions of eMule",
    4711: "eMule optional web interface",
    4713: "PulseAudio sound server",
    4723: "Appium open source automation tool",
    4728: "Computer Associates Desktop and Server Management (DMP)/Port Multiplexer",
    4730: "Gearman's job server",
    4739: "IP Flow Infromation Export",
    4747: "Apprentice",
    4753: "SIMON (service and discovery)",
    4789: "Virtual eXtensible Local Area Network (VXLAN)",
    4791: "IP Routable RocE (RoCEv2)",
    4840: "OPC UA Connection Protocol (TCP) and OPC UA Multicast Datagram Protocol (UDP) for OPC Unified Architecture from OPC Foundation",
    4843: "OPC UA TCP Protocol over TLS/SSL for OPC Unified Architecture fromOPC Foundation",
    4847: "Web Fresh Communication",
    4848: "Java, Glassfish Application Server admin default",
    4894: "LysKOM Protocol A",
    4944: "DrayTek DSL Status Monitoring",
    4949: "Munin Resource Monitoring Tool",
    4950: "Cylon Controls UC32 Communications Port",
    5000: "UPnP - Windows network device ineroperability // VTun, VPN Software // ASP.NET Core Dev Webserver // FlightGear Multiplayer // Synology Inc. Management Console, File Station, Audio Station // Flask Developement Web Server // Heroku console access // Docker Registry // AT&T U-verse public, educational and government access (PEG) streaming over HTTP // High-Speed SECS Mesasge Services // 3CX Phone System Legacy Management Console // RidgeRun GStreamer Daemon (GSTD) // Apple AirPlay Reciever // League of Legends",
    5001: "Slingbox // Iperf(Tool for measuring TCP and UDP bandwidth performace) // Synology Inc Secured Management Console, Secure API // 3CX Phone System Secured Management Console, Secure API",
    5002: "ASSA ARX access control system",
    5003: "FileMaker - name binding and transport",
    5004: "Real-time Transport Protocol media data (RTP)",
    5005: "Real-time Transport Protocol control protocol (RTCP)",
    5007: "Palo Alto Networks - User-ID agaent",
    5010: "TelePath (the IBM FlowMark workflow-management-system messaging platform) The TCP port is used for IBM WebSphere MQ WorkFlow",
    5011: "TelePath (the IBM FlowMark workflow-management-system messaging  platform)",
    5025: "scpi-raw Standard Commands for Programmable Instruments",
    5029: "Sonic Robo Blask 2 and Sonic Robo Blast 2 Kart servers",
    5031: "AVM CAPI-over-TCP (ISDN over Ethernet tunneling)",
    5037: "Android ADB server",
    5044: "Standard port in Filebeats/Logstash implementation of Lumberjack protocol",
    5048: "Texai Message Service",
    5050: "Yahoo! Messenger",
    5051: "ita-agent Symantec Intruder Alert",
    5060: "Session Initiation Protocol (SIP)",
    5061: "Session Initiation Protocol (SIP) over TLS",
    5062: "Localisation access",
    5064: "EPICS Channel Access server",
    5065: "EPICS Channel Access repeater beacon",
    5070: "Binary Floor Control Protocol (BFCP)",
    5084: "EPCglobal Low Level Reader Protocol (LLRP)",
    5085: "EPCglobal Low Level Reader Protocol (LLRP) over TLS",
    5090: "3CX Phone System 3CX Tunnel Protocol, 3CX App API, 3CX Session Border Controller",
    5093: "SafeNEt Inc Sentinel LM, Sentinel RMS, License Manager, client-to-server",
    5099: "SafeNet, Inc Sentinel LM, Sentinel RMS, License Manager, server-to-server",
    5104: "IMB Tivoli Framework",
    5121: "Neverwinter Nights",
    5124: "TorgaNET (Micronational Darknet)",
    5125: "TorgaNET (Micronation Itelligence Darknet)",
    5150: "ATMP Ascend Tunnel Management Protocol",
    5151: "ESRI SDE Instance // ESRI SDE Remote Start",
    5154: "BZFlag",
    5172: "PC over IP Endpoint Management",
    5190: "AOL Instant Messenger Protocol",
    5198: "EchoLink VoIP Amateur Radio Software (Voice)",
    5199: "EchoLink VoIP Amateur Radio Software (Voice)",
    5200: "EchoLink VoIP Amateur Radio Software (Information)",
    5201: "Iperf3 (Tool for measuring TCP and UDP bandwidth performance)",
    5222: "Extensible Messaging and Presence Protocol (XMPP) client connection",
    5223: "Apple Push Notification Service // Extensible Messaging and Presence Protocol (XMPP) client connection over SSL",
    5228: "HP Virtual Room Service // Google Play, Android Cloud to Device Messaging Service, Google Cloud Messaging",
    5242: "Viber",
    5243: "Viber",
    5246: "Control And Provisioning of Wireless Access Points (CAPWAP) CAPWP control",
    5247: "Control And Provisioning of Wireless Access Points (CAPWAP) CAPWAP data",
    5269: "Extensible Messaging and Presence Protocol (XMPP) server-to-server connection",
    5280: "Extensible Messaging and Presence Protocol (XMPP)",
    5281: "Extensible Messaging and Presence Protocol (XMPP)",
    5298: "Extensible Messaging and Presence Protocol (XMPP)",
    5310: "Outlaws - 1997 Video Game",
    5318: "Certificate Management over CMS",
    5349: "STUN over TLS/DTLS, a protocol for NAT tarversal // TURN over TLS/DTLS, a protocol for NAT traversal // STUN Behavior Discovery over TLS",
    5351: "NAT Port Mapping Protocol and Port Control Protocol—client-requested configuration for connections through network address translators and firewalls",
    5353: "Multicast DNS (mDNS)",
    5355: "Link-Local Multicast Name Resolution (LLMNR), allows hosts to perform name resolution for hosts on the same local link (only provided by Windows Vista and Server 2008)",
    5357: "Web Services for Devices (WSDAPI) (only provided by Windows Vista, Windows 7 and Server 2008)",
    5358: "WSDAPI Applications to Use a Secure Channel (only provided by Windows Vista, Windows 7 and Server 2008)",
    5394: "Kega Fusion, a Sega multi-console emulator",
    5402: "Multicast File Transfer Protocol (MFRP)",
    5405: "NetSupport Manager",
    5412: "IBM Rational Synergy (Telelogic Synergy)(Continuous CM) Message Router",
    5413: "WonderShare SuiteLink service",
    5417: "SNS Agent",
    5421: "NetSupport Manager",
    5432: "PostgreSQL database system",
    5433: "bouwsoft file/webserver",
    5445: "Cisco Unified Video Advantage",
    5450: "OSIsoft PI Server Client Access",
    5457: "OSIsoft PI Framework Client Access",
    5458: "OSIsoft PI Notifiactions Client Access",\
    5480: "VMWare VAMI (Virtual Appliance Management Infrastucture)",
    5481: "Schneider Electric's ClearSCADA (SCADA implementation for Windows)",
    5495: "IBM Cognos TM1 Admin server",
    5498: "Hotline tracker server connection",
    5499: "Hotline tracker server discovery",
    5500: "League of Lengends // VNC Remote Frame Buffer RFB protocol - for incoming listening viewer",
    5501: "Hotline file transfer connection",
    5517: "Setiqueue Proxy server client for SET@Home project",
    5550: "Hewlett-Packard Data Protector",
    5554: "Fastboot default wireless port",
    5555: "Oracle WebCenter Content: Inbound Refinery - Intradoc Socket port. // Freeciv versions up to 2.0, Hewlet Packard Data Protector, MacAfee Endpoint Encrtyption Database Server, SAP, Default for Microsoft Dynamics CRM 4.0, Softether VPN default port",
    5556: "Freeciv, Oracle WebLogic Server Node Manager",
    5568: "Session Data Transport (SDT) - part of Architecture for Control Networks (ACN)",
    5601: "Kibana",
    5631: "pcANYWHEREdata, Symantec pcAnywhere (version 7.52 and later) data",
    5632: "pcANYWHEREstat, Symantec pcAnywhere (version 7.52 and later) status",
    5656: "IBM Lotus Sametime p2p file transfer",
    5666: "NRPE (Nagios)",
    5667: "NSCA (Nagios)",
    5670: "FILEMQ ZeroMQ File Message Queuing Protocol // ZRE-DISC ZeroMQ Realtime Exchange Protocol (Discovery)",
    5671: "Advanced Message Queuing Protocol (AMQP) over TLS",
    5672: "Advanced Message Queuing Protocol (AMQP)",
    5683: "Constrained Application protocol (CoAP)",
    5684: "Constrained Application protocol Secure (CoAP)",
    5693: "Nagios Cross Platform Agent (NCPA)",
    5701: "Hazelcast default communication port",
    5718: "Microsoft DPM Data Channel (with the agent coordinator)",
    5719: "Microsoft RPC, DFSR (SYSVOL) Replication Sevice",
    5722: "Microsoft RPC, DFSR (SYSVOL) Replication Service",
    5723: "System Center Operations Manager",
    5724: "Operations Manager Console",
    5741: "IDA Discover Port 1",
    5742: "IDA Discover Port 2",
    5800: "VNC Remote Frame Buffer RFB protocol over HTTP // ProjectWise Server",
    5900: "Remote Frame Buffer protocol (RFB) // Virtual Network Computing (VNC) Remote Frame Buffer RFB protocol",
    5905: "Windows service - C:\Program Files\Intel\Intel(R) Online Connect Access\IntelTechnologyAccessService.exe - that listens on 127.0.0.1",
    5931: "AMMYY admin Remote Control",
    5938: "TeamViewer remote desktop protocol",
    5984: "CouchDB database server",
    5985: "Windows PowerShell Default psSession Port Windows Remote Management Service (WinRM-HTTP)",
    5986: "Windows PowerShell Default psSession Port Windows Remote Management Service (WinRM-HTTPS)",
    5988: "CIM-XML (DMTF Protocol)",
    5989: "CIM-XML (DMTF Protocol)",
    6000: "X11 - used between an X client and server over network",
    6005: "Default for BMC Software Control-M/Server—Socket used for communication between Control-M processes—though often changed during installation // Default for Camfrog chat & cam client",
    6009: "JD Edwards EnterpriseOne ERP system JDENet messaging client listener",
    6050: "Arcserve backup",
    6051: "Arcserve backup",
    6063: "X11 - used between an X client and server over network",
    6086: "Peer Distributed Transfer Protocol (PDTP), FTP like file server in a P2P network",
    6100: "Vizrt System // Ventrilo authentication for version 3",
    6101: "Backup Exec Agent Browser",
    6110: "softcm, HP Softbench CM",
    6111: "spc, HP Softbench Sub-Process Control",
    6112: "dtspcd, execute commands and launch applications remotely // Blizzard's Battle.net gaming service and some games, ArenaNet gaming service, Relic gaming service // Club Penguin Disney online game for kids",
    6113: "Club Penguin Disney online game for kids, Used by some Blizzard games",
    6136: "ObjectDB database server",
    6159: "ARINC 840 EFB Application Control Interface",
    6200: "Oracle WebCenter Content Portable: Content Server (With Native UI) and Inbound Refinery",
    6201: "Thermo-Calc Software AB: Management of service nodes in a processing grid for thermodynamic calculations // Oracle WebCenter Content Portable: Admin",
    6225: "Oracle WebCenter Content Portable: Content Server Web UI",
    6227: "Oracle WebCenter Content Portable: JavaDB",
    6240: "Oracle WebCenter Content Portable: Capture",
    6244: "Oracle WebCenter Content Portable: Content Server—Intradoc Socket port",
    6255: "Oracle WebCenter Content Portable: Inbound Refinery—Intradoc Socket port",
    6257: "WinMX",
    6260: "planet M.U.L.E.",
    6262: "Sybase Advantage Database Server",
    6343: "SFlow, sFlow traffic monitoring",
    6346: "gnutella-svc, gnutella (FrostWire, Limewire, Shareaza, etc.)",
    6350: "App Discovery and Access Protocol",
    6379: "Redis key-value data store",
    6389: "EMC CLARiiON",
    6432: "PgBouncer—A connection pooler for PostgreSQL",
    6436: "Leap Motion Websocket Server TLS",
    6437: "Leap Motion Websocket Server",
    6443: "Kubernetes API server",
    6444: "Sun Grid Engine Qmaster Service",
    6445: "Sun Grid Engine Execution Service",
    6463: "Discord RPC",
    6464: "Port assignment for medical device communication in accordance to IEEE 11073-20701",
    6472: "Discord RPC",
    6502: "Netop Remote Control",
    6513: "NETCONF over TLS",
    6514: "Syslog over TLS",
    6515: "Elipse RPC Protocol (REC)",
    6516: "Windows Admin Center",
    6543: "Pylons project#Pyramid Default Pylons Pyramid web service port",
    6556: "Check MK Agent",
    6566: "SANE (Scanner Access Now Easy)—SANE network scanner daemon",
    6560: "Speech-Dispatcher daemon",
    6561: "Speech-Dispatcher daemon",
    6571: "Windows Live FolderShare client",
    6600: "Microsoft Hyper-V Live // Music Player Daemon (MPD)",
    6601: "Microsoft Forefront Threat Management Gateway",
    6602: "Microsoft Windows WSS Communication",
    6619: "odette-ftps, Odette File Transfer Protocol (OFTP) over TLS/SSL",
    6622: "Multicast FTP",
    6653: "OpenFlow",
    6660: "Internet Relay Chat (IRC)",
    6664: "Internet Relay Chat (IRC)",
    6665: "Internet Relay Chat (IRC)",
    6669: "Internet Relay Chat (IRC)",
    6679: "Osorno Automation Protocol (OSAUT) // Internet Relay Chat (IRC) SSL (Secure Internet Relay Chat)—often used",
    6690: "Synology Cloud station",
    6697: "IRC SSL (Secure Internet Relay Chat)—often used",
    6699: "WinMX",
    6715: "AberMUD and derivatives default port",
    6771: "BitTorrent Local Peer Discovery",
    6783: "Splashtop Remote server broadcast",
    6785: "Splashtop Remote server broadcast",
    6801: "ACNET Control System Protocol",
    6881: "BitTorrent part of full range of ports used most often",
    6887: "BitTorrent part of full range of ports used most often",
    6888: "MUSE // BitTorrent part of full range of ports used most often",
    6889: "BitTorrent part of full range of ports used most often",
    6890: "BitTorrent part of full range of ports used most often",
    6891: "BitTorrent part of full range of ports used most often // Windows Live Messenger (File transfer)",
    6900: "BitTorrent part of full range of ports used most often // Windows Live Messenger (File transfer)",
    6901: "Windows Live Messenger (Voice) // BitTorrent part of full range of ports used most often",
    6902: "BitTorrent part of full range of ports used most often",
    6924: "split-ping, ping with RX/TX latency/loss split",
    6968: "BitTorrent part of full range of ports used most often",
    6969: "acmsoda // Bittorrent tracker",
    6970: "BitTorrent part of full range of ports used most often // QuickTime Streaming Server",
    6999: "BitTorrent part of full range of ports used most often // QuickTime Streaming Server",
    7000: "Default for Vuze's built-in HTTPS Bittorrent tracker // Avira Server Management Console",
    7001: "Avira Server Management Console // Default for BEA WebLogic Server's HTTP server, though often changed during installation",
    7002: "Default for BEA WebLogic Server's HTTPS server, though often changed during installation",
    7005: "Default for BMC Software Control-M/Server and Control-M/Agent for Agent-to-Server, though often changed during installation",
    7006: "Default for BMC Software Control-M/Server and Control-M/Agent for Server-to-Agent, though often changed during installation",
    7010: "Default for Cisco AON AMC (AON Management Console)",
    7022: "Database mirroring endpoints",
    7023: "Bryan Wilcutt T2-NMCS Protocol for SatCom Modems",
    7025: "Zimbra LMTP [mailbox]—local mail delivery",
    7047: "Zimbra conversion server",
    7070: "Real Time Streaming Protocol (RTSP), used by QuickTime Streaming Server. TCP is used by default, UDP is used as an alternate",
    7133: "Enemy Territory: Quake Wars",
    7144: "Peercast",
    7145: "Peercast",
    7171: "Tibia",
    7262: "CNAP (Calypso Network Access Protocol)",
    7272: "WatchMe - WatchMe Monitoring",
    7306: "Zimbra mysql [mailbox]",
    7307: "Zimbra mysql [logger]",
    7312: "Sibelius License Server",
    7396: "Web control interface for Folding@home v7.3.6 and later",
    7400: "RTPS (Real Time Publish Subscribe) DDS Discovery",
    7401: "RTPS (Real Time Publish Subscribe) DDS User-Traffic",
    7402: "RTPS (Real Time Publish Subscribe) DDS Meta-Traffic",
    7471: "Stateless Transport Tunneling (STT)",
    7473: "Rise: The Vieneo Province",
    7474: "Neo4J Server webadmin",
    7478: "Default port used by Open iT Server",
    7542: "Saratoga file transfer protocol",
    7547: "CPE WAN Management Protocol (CWMP) Technical Report 069",
    7575: "Populous: The Beginning server",
    7624: "Instrument Neutral Distributed Interface",
    7631: "ERLPhase",
    7634: "hddtemp—Utility to monitor hard drive temperature",
    7652: "I2P anonymizing overlay network",
    7654: "I2P anonymizing overlay network",
    7655: "I2P SAM Bridge Socket API",
    7656: "I2P anonymizing overlay network",
    7660: "I2P anonymizing overlay network",
    7670: "BrettspielWelt BSW Boardgame Portal",
    7680: "Delivery Optimization for Windows 10",
    7687: "Bolt database connection",
    7707: "Killing Floor",
    7708: "Killing Floor",
    7717: "Killing Floor",
    7777: "iChat server file transfer proxy // Oracle Cluster File System 2 // Windows backdoor program tini.exe default // Just Cause 2: Multiplayer Mod Server // Terraria default server // San Andreas Multiplayer (SA-MP) default port server // SCP: Secret Laboratory Multiplayer Server",

}   